language: node_js

node_js:
 - 0.10

cache: apt

notifications:
    email:
        - me@lmorchard.com

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential libzmq-dev nodejs-legacy
