language: node_js

node_js:
 - 0.10

cache: apt

notifications:
    email:
        - me@lmorchard.com

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libzmq3-dev
    - mkdir data
    - wget https://www.fuzzwork.co.uk/dump/sqlite-latest.sqlite.bz2
    #- wget http://lmorchard.com/eve/sqlite-latest.sqlite.bz2
    - bunzip2 sqlite-latest.sqlite.bz2
    - mv sqlite-latest.sqlite data
